name: Build Brut

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install build tools and dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential clang cmake ninja-build libglm-dev \
          libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev \
          libxss-dev libwayland-dev libxkbcommon-dev wayland-protocols libdrm-dev

    - name: Clone and build SDL3
      run: |
        git clone https://github.com/libsdl-org/SDL.git
        cd SDL
        mkdir build && cd build
        cmake .. -G Ninja -DSDL_VENDOR_INFO="CI-Build"
        ninja
        sudo ninja install
        sudo ldconfig

    - name: Give execute permission to LinuxBuild
      run: chmod +x MakeDesktop.sh

    - name: Compile the project
      run: |
        echo "Starting the build process..."
        ./MakeDesktop.sh
        echo "Build finished."

    - name: Upload compiled binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: brut
        path: brut